using ExcelToFlatFileFramework.Domain.Attributes;

namespace ExcelToFlatFileFramework.Domain.OutTemplates.PartDefinition
{
    public class _122_XROTABLE
    {
        [AmosOutputLength(32)]
        public string PartNo { get; set; } //[32]
        [AmosOutputLength(20)]
        public string SerialNo { get; set; } //[20]
        [AmosOutputLength(12)]
        public string Owner { get; set; } //[12]
        [AmosOutputLength(10)]
        public string DelDate { get; set; } //[10]
        [AmosOutputLength(10)]
        public string MfgDate { get; set; } //[10]
        [AmosOutputLength(8)]
        public string LabelNo { get; set; } //[8]
        [AmosOutputLength(6)]
        public string Aircraft { get; set; } //[6]
        [AmosOutputLength(14)]
        public string Position { get; set; } //[14]
        [AmosOutputLength(4)]
        public string Station { get; set; } //[4]
        [AmosOutputLength(8)]
        public string Store { get; set; } //[8]
        [AmosOutputLength(16)]
        public string Location { get; set; } //[16]
        [AmosOutputLength(12)]
        public string Entity { get; set; } //[12]
        [AmosOutputLength(10)]
        public string ReadoutDate { get; set; } //[10]
        [AmosOutputLength(10)]
        public string TahInst { get; set; } //[10]
        [AmosOutputLength(6)]
        public string TacInst { get; set; } //[6]
        [AmosOutputLength(10)]
        public string Tsn { get; set; } //[10]
        [AmosOutputLength(6)]
        public string Csn { get; set; } //[6]
        [AmosOutputLength(2)]
        public string Condition { get; set; } //[2]
        [AmosOutputLength(10)]
        public string LastOhDate { get; set; } //[10]
        [AmosOutputLength(1)]
        public string OhDateUnk { get; set; } //[1]
        [AmosOutputLength(6)]
        public string LastOhCycles { get; set; } //[6]
        [AmosOutputLength(1)]
        public string OhCyclesUnk { get; set; } //[1]
        [AmosOutputLength(10)]
        public string LastOhTsn { get; set; } //[10]
        [AmosOutputLength(1)]
        public string OhTsnUnk { get; set; } //[1]
        [AmosOutputLength(10)]
        public string LastRepDate { get; set; } //[10]
        [AmosOutputLength(1)]
        public string RepDateUnk { get; set; } //[1]
        [AmosOutputLength(6)]
        public string LastRepCycles { get; set; } //[6]
        [AmosOutputLength(1)]
        public string RepCyclesUnk { get; set; } //[1]
        [AmosOutputLength(10)]
        public string LastRepTsn { get; set; } //[10]
        [AmosOutputLength(1)]
        public string RepTsnUnk { get; set; } //[1]
        [AmosOutputLength(10)]
        public string LastModDate { get; set; } //[10]
        [AmosOutputLength(1)]
        public string ModDateUnk { get; set; } //[1]
        [AmosOutputLength(6)]
        public string LastModCycles { get; set; } //[6]
        [AmosOutputLength(1)]
        public string ModCyclesUnk { get; set; } //[1]
        [AmosOutputLength(10)]
        public string LastModTsn { get; set; } //[10]
        [AmosOutputLength(1)]
        public string ModTsnUnk { get; set; } //[1]
        [AmosOutputLength(40)]
        public string OldLabelNo { get; set; } //[40]
        [AmosOutputLength(1)]
        public string TsnUnknown { get; set; } //[1]
        [AmosOutputLength(1)]
        public string CsnUnknown { get; set; } //[1]
        [AmosOutputLength(1)]
        public string MfgUnknown { get; set; } //[1]
    }
}
