namespace ExcelToFlatFileFramework.Domain.OutTemplates.PartDefinition
{
    public class _407_XHISTORY
    {
        public string PARTNO { get; set; } //[32][m]
        public string SERIALNUMBER { get; set; } //[20]
        public string RECEIVER { get; set; } //[12]
        public string TRANS_DATE { get; set; } //[10][m]
        public string TRANS_TYPE { get; set; } //[2][m]
        public string TAH { get; set; } //[14]
        public string TAC { get; set; } //[6]
        public string TSN { get; set; } //[14]
        public string TBI { get; set; } //[14]
        public string CBI { get; set; } //[6]
        public string CSN { get; set; } //[6]
        public string CONDITION { get; set; } //[2][m]
        public string REL_FLAG { get; set; } //[6]
        public string CONFIRMED { get; set; } //[2]
        public string BOOKED_BY { get; set; } //[8]
        public string BOOKING_DATE { get; set; } //[10]
        public string QTY { get; set; } //[14]
        public string VOUCHERNO { get; set; } //[20]
        public string ORDERNO { get; set; } //[10]
        public string HI_TEXT_KEY { get; set; } //[20]
        public string LABELNO { get; set; } //[8]
        public string CUST_WO { get; set; } //[20]
        public string STATION { get; set; } //[4]
        public string STORE { get; set; } //[10]
        public string LOCATION { get; set; } //[16]
        public string POSITION { get; set; } //[14]
        public string ORDERDATE { get; set; } //[10]
        public string GIGHER_PARTNO { get; set; } //[32]
        public string HIGHER_SERIALNO { get; set; } //[20]
        public string UNIQUE_ROT_ID { get; set; } //[20]
        public string MAT_CLASS { get; set; } //[4]
        public string AVERAGE_PRICE { get; set; } //[14]
        public string REPAIRABLE { get; set; } //[1]
        public string MFG_DATE { get; set; } //[10]
        public string BATCHNO { get; set; } //[20]
        public string ATA_CHAPTER { get; set; } //[12]
        public string ENTITY { get; set; } //[12]
        public string PROJECTNO { get; set; } //[14]
        public string STATUS { get; set; } //[4]
        public string CR_ISNEW { get; set; } //[2]
        public string OWNER { get; set; } //[12]
    }
}
