using ExcelToFlatFileFramework.Domain.Attributes;

namespace ExcelToFlatFileFramework.Domain.OutTemplates.PartDefinition
{
    public class _407_XHISTORY
    {
        [AmosOutputLength(32)]
        public string PartNo { get; set; } //[32]
        [AmosOutputLength(20)]
        public string SerialNumber { get; set; } //[20]
        [AmosOutputLength(12)]
        public string Receiver { get; set; } //[12]
        [AmosOutputLength(10)]
        public string TransDate { get; set; } //[10]
        [AmosOutputLength(2)]
        public string TransType { get; set; } //[2]
        [AmosOutputLength(14)]
        public string Tah { get; set; } //[14]
        [AmosOutputLength(6)]
        public string Tac { get; set; } //[6]
        [AmosOutputLength(14)]
        public string Tsn { get; set; } //[14]
        [AmosOutputLength(14)]
        public string Tbi { get; set; } //[14]
        [AmosOutputLength(6)]
        public string Cbi { get; set; } //[6]
        [AmosOutputLength(6)]
        public string Csn { get; set; } //[6]
        [AmosOutputLength(2)]
        public string Condition { get; set; } //[2]
        [AmosOutputLength(6)]
        public string RelFlag { get; set; } //[6]
        [AmosOutputLength(2)]
        public string Confirmed { get; set; } //[2]
        [AmosOutputLength(8)]
        public string BookedBy { get; set; } //[8]
        [AmosOutputLength(10)]
        public string BookingDate { get; set; } //[10]
        [AmosOutputLength(14)]
        public string Qty { get; set; } //[14]
        [AmosOutputLength(20)]
        public string VoucherNo { get; set; } //[20]
        [AmosOutputLength(10)]
        public string OrderNo { get; set; } //[10]
        [AmosOutputLength(20)]
        public string HiTextKey { get; set; } //[20]
        [AmosOutputLength(8)]
        public string LabelNo { get; set; } //[8]
        [AmosOutputLength(20)]
        public string CustWo { get; set; } //[20]
        [AmosOutputLength(4)]
        public string Station { get; set; } //[4]
        [AmosOutputLength(10)]
        public string Store { get; set; } //[10]
        [AmosOutputLength(16)]
        public string Location { get; set; } //[16]
        [AmosOutputLength(14)]
        public string Position { get; set; } //[14]
        [AmosOutputLength(10)]
        public string OrderDate { get; set; } //[10]
        [AmosOutputLength(32)]
        public string GigherPartNo { get; set; } //[32]
        [AmosOutputLength(20)]
        public string HigherSerialNo { get; set; } //[20]
        [AmosOutputLength(20)]
        public string UniqueRotId { get; set; } //[20]
        [AmosOutputLength(4)]
        public string MatClass { get; set; } //[4]
        [AmosOutputLength(14)]
        public string AveragePrice { get; set; } //[14]
        [AmosOutputLength(1)]
        public string Repairable { get; set; } //[1]
        [AmosOutputLength(10)]
        public string MfgDate { get; set; } //[10]
        [AmosOutputLength(20)]
        public string BatchNo { get; set; } //[20]
        [AmosOutputLength(12)]
        public string AtaChapter { get; set; } //[12]
        [AmosOutputLength(12)]
        public string Entity { get; set; } //[12]
        [AmosOutputLength(14)]
        public string ProjectNo { get; set; } //[14]
        [AmosOutputLength(4)]
        public string Status { get; set; } //[4]
        [AmosOutputLength(2)]
        public string CrIsNew { get; set; } //[2]
        [AmosOutputLength(12)]
        public string Owner { get; set; } //[12]
    }
}
